### PR TITLE
Pull request for 2 changes to make current Go work

### PR DESCRIPTION
**Pull request by bketelsen**
Changed logging to new format and changed slice allocation to new format.  Thanks for the library!

### CODE REVIEW

**Comment by Philio** [comment]
Hi, I'm looking at pulling this into my original branch. 1 question - which platform uses /tmp/mysql.sock for the MySQL socket? It perhaps needs some additional nodes about alternative "defaults" for this. The default socket path in the original code works for Debian/Ubuntu.

**Comment by bketelsen** [comment]
My apologies, the /tmp/mysql.sock path works for Mac/Darwin, and I couldn't get a connection without specifying a socket because the database was on the same machine as the application.  i'm not very well versed in mysql connections, could one do a connection without a socket to a local mysql instance if there were no socket present?

**Comment by Philio** [comment]
Yes you can do a TCP/IP connection to MySQL locally, however generally if you're using localhost the norm is to use the socket.
I'll not commit the Mac specific sockets but will add in the other changes later, thanks :)

**Comment by Philio** [comment]
I've updated release to work with the latest go now.

**Pull request closed without merging**
